[project]
name = "extracao-clinicaltrials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eduardo Augusto Rabelo Socca", email = "eduardo_socca@yahoo.com.br" }
]
requires-python = ">=3.13"
dependencies = [
    "altair>=5.0.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "python-pptx>=1.0.2",
    "reportlab>=5.0.1",
    "requests>=2.34.2",
    "streamlit>=1.38.0",
    "vl-convert-python>=1.9.0.post1",
]

[project.scripts]
extracao-clinicaltrials = "extracao_clinicaltrials:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
